server:
  port: 8888
spring:
  application:
    name: mall-config-server
  security:
    user:
      name: admin
      password: iABvsHDmjD
  cloud:
    config:
#    远程仓库的分支
      label: master
      server:
        git:
#        访问git仓库的用户名 公开仓库不需要填写用户名和密码 私有仓库需要填写
          username:
#          访问仓库的密码
          password:
#          git仓库地址
          uri: https://github.com/emptyNotFish/okdeer/
#          配置仓库路径
          search-paths: config
eureka:
  client:
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@master.okdeer.com:11001/eureka/,http://${spring.security.user.name}:${spring.security.user.password}@slave1.okdeer.com:11002/eureka/

