server:
  port: 8881
spring:
  application:
    name: mall-config-server
  cloud:
    config:
#    远程仓库的分支
      label: master
#      配置的环境 dev开发环境配置文件  test测试环境  pro正式环境
      profile: dev
#      配置服务中心的网址
      uri: http://localhost:8888/

